### Numpy

### https://numpy.org/doc/stable/reference/index.html

In [1]:
# pip install numpy
import numpy as np
import sys 
import time

### Time and Memory

In [47]:
number = 10000000 
large_list = list(range(number))
large_array = np.arange(number)

items = sum(sys.getsizeof(x) for x in large_list)
list_size = sys.getsizeof(large_list) + items 

array_size = large_array.nbytes 

print(f"list size: {list_size}")
print(f"array size: {array_size}")

list size: 360000052
array size: 80000000


In [48]:
start_time = time.time()
sum(large_list)
end_time = time.time()
print(end_time - start_time)

0.10892581939697266


In [49]:
start_time = time.time()
np.sum(large_array)
end_time = time.time()
print(end_time - start_time)

0.01007390022277832


#### Create Numpy Array

In [53]:
list1 = [12, 13, 5, 90]
print(type(list1))
arr1 = np.array(list1)
print(arr1)
arr1
print(type(arr1))

<class 'list'>
[12 13  5 90]
<class 'numpy.ndarray'>


In [54]:
t1 = (12, 13, 5, 90)
arr2 = np.array(t1)
arr2

array([12, 13,  5, 90])

In [56]:
#help(np.array)

#### Type

#### NumPy's Type Flexibility: NumPy Automatic Upcasting

In [57]:
list1 = [12, 10.4, "python"]
print(list1)

[12, 10.4, 'python']


In [59]:
list1 = [12, 3.8, 12.6, 10, "python"]
arr1 = np.array(list1)
arr1

array(['12', '3.8', '12.6', '10', 'python'], dtype='<U32')

    Signed Integers:
        np.int8 ('i1'): 8-bit integer. Range: -128 to 127.
        np.int16 ('i2'): 16-bit integer. Range: -32,768 to 32,767.
        np.int32 ('i4'): 32-bit integer. Range: -2,147,483,648 to 2,147,483,647.
        np.int64 ('i8'): 64-bit integer. Range: -9,223,372,036,854,775,808 to 9,223,372,036,854,775,807.
        np.int_: Alias for np.int64 (or the largest integer type available).

    Unsigned Integers:
        np.uint8 ('u1'): 8-bit unsigned integer. Range: 0 to 255.
        np.uint16 ('u2'): 16-bit unsigned integer. Range: 0 to 65,535.
        np.uint32 ('u4'): 32-bit unsigned integer. Range: 0 to 4,294,967,295.
        np.uint64 ('u8'): 64-bit unsigned integer. Range: 0 to 18,446,744,073,709,551,615.

Floating Point Types

    np.float16 ('f2'): 16-bit half precision float.
    np.float32 ('f4'): 32-bit single precision float.
    np.float64 ('f8'): 64-bit double precision float.
    np.float_: Alias for np.float64.

Boolean Type

Used for true/false values.

    np.bool_: Boolean type.

String Types

For character data.

    np.string_ ('S'): Fixed-length string type (ASCII).
    np.unicode_ ('U'): Fixed-length Unicode string type.



#### dtype

In [64]:
arr1 = np.array([12, 34.9, 57])
print(type(arr1))
print(arr1.dtype)

<class 'numpy.ndarray'>
float64


In [65]:
arr2 = np.array([23.5, 2., 5])
print(type(arr2))
print(arr2.dtype)

<class 'numpy.ndarray'>
float64


#### Changing the data type

#### astype()

In [69]:
arr1 = np.array([12, 34.9, 57])
arr1 = arr1.astype("f2")
print(arr1.dtype)

float16


### dtype

In [71]:
arr1 = np.array([12, 34, 57], dtype="i2")
print(arr1.dtype)

int16


#### Shape

In [74]:
# 0D array (scalar)
arry_0d = np.array(10)
arry_0d
print(arry_0d.shape)
print(arry_0d.ndim)

()
0


In [76]:
# 1D array
arr_1d = np.array([12, 23, 10])
print(arr_1d.shape)
print(arr_1d.ndim)

(3,)
1


In [80]:
# 2D array (Matrix)
arr_2d = np.array([
    [18, 23, 19],
    [10, 29, 20]
])
print(arr_2d.shape)
print(arr_2d.ndim)
arr_2d
result = arr_2d.shape
print(result, type(result), len(result))

(2, 3)
2
(2, 3) <class 'tuple'> 2


In [82]:
# 3D array 
arr_3d = np.array([
    [[12, 78, 20],[56, 45, 23]],
    [[12, 78, 20],[12, 78, 20]]
])
print(arr_3d.shape)
print(arr_3d.ndim)

(2, 2, 3)
3


#### Order

In [83]:
arr1 = np.array([
    [39,20], 
    [3, 12]], order="C")
arr2 = np.array([
    [39,20], 
    [3, 12]], order="F")
arr1, arr2

(array([[39, 20],
        [ 3, 12]]),
 array([[39, 20],
        [ 3, 12]]))

In [84]:
arr1 = arr1.flatten(order="C")
arr1

array([39, 20,  3, 12])

In [85]:
arr2 = arr2.flatten(order="F")
arr2

array([39,  3, 20, 12])

#### Indexing

In [86]:
arr_1d = np.array([10, 20, 30])
print(arr_1d[0])

10


In [89]:
arr_2d = np.array([[10, 20], [30,40]], dtype=np.int8)
arr_2d[0]
arr_2d[1, 0]

30

In [93]:
# 3D array 
arr_3d = np.array([
    [[1],[2]],
    [[3], [4]]
])
arr_3d[0, 1, 0]

2

#### Slicing

In [95]:
arr_1d = np.array([10, 20, 30, 40, 50])
arr_1d[1:4:2] # 1, 3

array([20, 40])

In [103]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
arr_2d[0:2, 1:3]

array([[2, 3],
       [5, 6]])

In [101]:
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6],[7, 8]]])
arr_3d[:, 0, 0]

array([1, 5])

### Filtering

In [106]:
arr_1d = np.array([20, 30, 40, 50])
arr2 = np.array([1, 0, 1, 2]) 
arr3 = arr_1d[arr2]
arr_1d[[0, 2, 3]]

array([20, 40, 50])

In [107]:
arr2 = np.array([2, 3, 18, 19, 23, 17])
result = arr2 > 10 
print(result)

[False False  True  True  True  True]


In [108]:
arr2 = np.array([2, 3, 18, 19, 23, 17])
result = arr2[arr2 > 10]
print(result)

[18 19 23 17]


In [109]:
arr2 = np.array([2, 3, 18, 19, 23, 17])
result = arr2[arr2 % 2 != 0]
print(result)

[ 3 19 23 17]


#### Operations

1. Arithmetic Operations


In [113]:
# +, *, -, /
arr1 = np.array([[1, 2],[3, 4]]) # 2, 2
arr2 = np.array([2, 10])

result = arr1 + arr2 
result

array([[ 3, 12],
       [ 5, 14]])

2. Logical Operations

In [116]:
arr1 = np.array([True, True])
arr2 = np.array([False, True])
arr3 = arr1 | arr2 
arr4 = arr1 & arr2 
arr5 = ~arr1
arr3, arr4, arr5

(array([ True,  True]), array([False,  True]), array([False, False]))

3. Comparison Operations

In [119]:
## >, <, <=, >=, ==, !=
arr1 = np.array([3, 5, 7, 20, 20, 20])
arr2 = arr1[arr1==20]
print(arr2)
result = arr1==20
result2 = np.sum(arr1==20)
result2

[20 20 20]


3

### axis

In [122]:
m1 = np.array([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]])

sum_data = np.sum(m1)
sum_columns = np.sum(m1, axis=0)
sum_rows = np.sum(m1, axis=1)
sum_rows

array([ 6, 15, 24])

### Vectorize

In [123]:
def custom_operation(x):
    if x > 0:
        return x ** 2
    elif x < 0:
        return abs(x)
    else:
        return 0

In [124]:
arr1 = np.array([3, -4, -5, 12, 1, 0])
v_function = np.vectorize(custom_operation)
result = v_function(arr1)
print(result)

[  9   4   5 144   1   0]


In [126]:
def compaire(p1, p2):
    if p1 > p2:
        return "INC"
    elif p2 > p1:
        return "DEC"
    else:
        return "Unchanged"

In [127]:
last_year = np.array([150, 200, 300, 400, 500])
this_year = np.array([100, 190, 300, 450, 520])
v_function = np.vectorize(compaire)
result = v_function(this_year, last_year)
result

array(['DEC', 'DEC', 'Unchanged', 'INC', 'INC'], dtype='<U9')

### Where

In [128]:
arr = np.array([1, 2, 3, 4, 500])
result = np.where(arr>3)
result

(array([3, 4]),)

In [130]:
arr1 = np.array([1, 2, 3, 4, 500])
arr2 = np.array([10, 20, 30, 40, 50])
result = np.where(arr2 > arr1, arr2*2, -arr2)
result

array([ 20,  40,  60,  80, -50])

### all , any

In [132]:
arr1 = np.array([True, False, True, True])
result_all = np.all(arr1)
result_any = np.any(arr1)
result_all, result_any

(False, True)

### copy and view

In [133]:
orginal_arr = np.array([[2, 3], [4, 5]])
copy_arr = orginal_arr.copy()
orginal_arr[0, 0] = 200 
orginal_arr, copy_arr

(array([[200,   3],
        [  4,   5]]),
 array([[2, 3],
        [4, 5]]))

In [134]:
orginal_arr = np.array([2, 3, 4, 5])
v_arr = orginal_arr.view()
orginal_arr[1] = 450
orginal_arr, v_arr

(array([  2, 450,   4,   5]), array([  2, 450,   4,   5]))

### Methods

1. Array Creation

In [135]:
arr1 = np.zeros((2, 2))
arr1

array([[0., 0.],
       [0., 0.]])

In [136]:
arr1 = np.ones((2, 2))
arr1

array([[1., 1.],
       [1., 1.]])

In [137]:
arr1 = np.full((2, 2), 5)
arr1

array([[5, 5],
       [5, 5]])

In [138]:
arr1 = np.eye(3)
arr1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [140]:
arr1 = np.arange(2, 8, 3) # 2, 5
arr1

array([2, 5])

In [141]:
arr1 = np.linspace(0, 1, 5)
arr1

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

2. Array Manipulation

In [145]:
arr1 = np.arange(6) # 6 
arr1
new_arr = arr1.reshape((2, 3))
print(new_arr)

[[0 1 2]
 [3 4 5]]


In [146]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.hstack((arr1, arr2))
arr3

array([1, 2, 3, 4, 5, 6])

In [147]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.vstack((arr1, arr2))
arr3

array([[1, 2, 3],
       [4, 5, 6]])

3. Mathematical Operations

In [150]:
res1 = np.add(2, 3)
np.sin(np.pi)

1.2246467991473532e-16

In [155]:
arr1 = np.array([1, 2, 3, 4, 5, 10])
np.min(arr1)
np.max(arr1)
np.mean(arr1)
np.median(arr1)

3.5

4. Logical Operations

In [156]:
arr1 = np.array([False, True, False])
arr2 = np.array([False, True, False])
np.logical_and(arr1, arr2)

array([False,  True, False])

In [157]:
# .npy
arr1 = np.array([3, 4, 10, 13, 19])
np.save('test.npy', arr1)

In [158]:
data = np.load("test.npy")
data

array([ 3,  4, 10, 13, 19])